main/urls.py
from django.urls import path
from main import views 

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

orders/urls.py
from django.urls import path
from orders import views 

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

from shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self: 
            return sum(cart.quantity for cart in self)
        return 0
    
class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(verbose_name="Требуеться доставка", default=False)
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(verbose_name="Оплата при получении", default=False)
    is_paid = models.BooleanField(verbose_name="Оплачено", default=False)
    status = models.CharField(max_length=50, verbose_name="Статус заказа", default="В обработке")
    
    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        
    def __str__(self):
        return f"Заказы № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
import re
from django import forms

class CreateOrderForm(forms.Form):
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices = [
            ("0", False),
            ("1", True)
        ]
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices = [
            ("0", 'False'),
            ("1", 'True')
        ]
    )
    
    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        
        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
        
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера")
        
        return data

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render

from carts.models import Cart

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem


@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # Создать заказ
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )
                        # Создать заказанные товары
                        for cart_item in cart_items:
                            product=cart_item.product
                            name=cart_item.product.name
                            price=cart_item.product.sell_price()
                            quantity=cart_item.quantity


                            if product.quantity < quantity:
                                raise ValidationError(f'Недостаточное количество товара {name} на складе\
                                                       В наличии - {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        # Очистить корзину пользователя после создания заказа
                        cart_items.delete()

                        messages.success(request, 'Заказ оформлен!')
                        return redirect('user:profile')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('orders:create_order')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            }

        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'Home - Оформление заказа',
        'form': form,
        'orders': True,
    }
    return render(request, 'orders/create_order.html', context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Выбранные товары</h3>
        <div class="container" id="cart-items-container">
            <!-- Разметка корзины -->
            {% user_carts request as carts %}
            {% include "carts/includes/included_cart.html" %}
            <!-- Закончилась разметка корзины -->
        </div>
    </div>
    <!-- Детали заказа -->
    <div class="container">
        <h3 class="text-center">Детали заказа</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url "orders:create_order" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name" required>
                            {% if form.first_name.errors %}
                                <div class='alert alert-danger alert-dismissible fade show'>
                                    {{form.first_name.errors}}
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*:</label>
                            <input type="text" class="form-control" id="id_last_name" 
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name" required>
                                {% if form.last_name.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.last_name.errors}}
                                    </div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                placeholder="В формате: XXX-XXX-XX-XX"
                                required>
                                {% if form.phone_number.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.phone_number.errors}}
                                    </div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Способ доставки: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Нужна
                                    доставка</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Адрес
                                доставки*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                name="delivery_address" rows="2"></textarea>
                                {% if form.delivery_address.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.delivery_address.errors}}
                                    </div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Способ оплаты: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">Оплата
                                    картой</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="1">
                                <label class="form-check-label" for="id_payment_on_get">Наличными/картой
                                    при плучении</label>
                                {% if form.payment_on_get.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.payment_on_get.errors}}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Оформить заказ</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}