carts/urls.py
from django.urls import path
from carts import views 

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path
from goods import views 

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.urls import path
from main import views 

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

from shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural= 'Категории'
    
    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', null=True, blank=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural= 'Продукты'
        ordering = ("id", )
    
    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug":self.slug})
    
    def display_id(self):
        return f'{self.id:05}'
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100, 2)
        
        return self.price

goods/views.py
from django.shortcuts import render, get_list_or_404
from django.core.paginator import Paginator

from goods.models import Products
from goods.utils import q_search

# Create your views here.
def catalog(request, category_slug=None):
    
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)
    
    
    if category_slug == 'all':
        goods = Products.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = get_list_or_404(Products.objects.filter(category__slug=category_slug))
    
    if on_sale:
        goods = goods.filter(discount__gt=0)
    
    if order_by and order_by != "default":
        goods = goods.order_by(order_by)
        
    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))
    
    context = {
        'title': 'Home - Каталог',
        'goods': current_page,
        'slug_url': category_slug,
    }
    return render(request, 'goods/catalog.html', context)

def product(request, product_slug):
    
    product = Products.objects.get(slug=product_slug)
    
    context = {
        'product': product
    }
    
    return render(request, 'goods/product.html', context=context)

goods/templates/goods/catalog.html
{% extends "base.html" %}

{% load static %}
{% load goods_tags %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{request.GET.q}}">
                {% endif %}
                
                <label class="form-check-label" for="flexCheckDefault">
                    Товары по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" 
                {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" 
                {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>

    {% if request.GET.q %}
    <h3 class='mt-4'>Результаты поиска по запросу {{ request.GET.q }}</h3>
    {% if not goods %}
        <link rel="stylesheet" href='{% static "deps/css/my_footer_css.css" %}'>
        <h2 class='mt-4'>По запросу ничего не найдено</h2>
    {% endif %}
    {% endif %}

    {% for product in goods %}
    <!-- Карта товара -->
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-primary rounded custom-shadow">
            {% if product.image %}
                <img src='{{ product.image.url }}' class="card-img-top" alt="{{ product.name }}">
            {% else %}
                <img src='{% static "deps/images/Not found image.png" %}' class="card-img-top" alt="{{ product.name }}">
            {% endif %}
            <div class="card-body">
                <a href="{% url 'catalog:product' product.slug %}">
                    <p class="card-title">
                        {% autoescape off %}
                        {% if product.headline %}
                            {{ product.headline }}
                        {% else %}
                            {{ product.name }}
                        {% endif %}
                        {% endautoescape %}
                    </p> 
                </a>
                <p class="card-text">
                    {% autoescape off %}
                        {% if product.bodyline %}
                            {{ product.bodyline|truncatechars:100 }}
                        {% else %}
                            {{ product.description|truncatechars:55 }}
                        {% endif %}
                    {% endautoescape %}
                </p>
                <p class="product_id">id: {{ product.display_id }}</p>
                <div class="d-flex justify-content-between">
                    {% if product.discount %}
                        <p><s>{{ product.price }}</s> $</p>
                        <p><strong>{{ product.sell_price }} $</strong></p>
                        <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                    {% else %}
                        <p><strong>{{ product.price }} $</strong></p>
                    {% endif %}
                    <a href="{% url "cart:cart_add" %}" class="btn add-to-cart" data-product-id="{{ product.id }}">
                        {% csrf_token %}
                        <img class="mx-1" src='{% static "deps/icons/cart-plus.svg"%}' alt="Catalog Icon"
                            width="32" height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
<!-- Пагинация -->
{% if goods %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not goods.has_previous %} disabled {% endif %}">
              <a class="page-link" href="{% if goods.has_previous %}?{% change_parms page=goods.previous_page_number %}{% else %}
              #
              {% endif %}
              ">Назад</a>
            </li>
            {% for page in goods.paginator.page_range %}
                <li class="page-item {% if goods.number == page %} active {% endif %}">
                    <a class="page-link" href="?{% change_parms page=page %}">{{ page }}</a>
                </li>
            {% endfor %}
            <li class="page-item {% if not goods.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if goods.has_next %}?{% change_parms page=goods.next_page_number %}{% else %}
                #
                {% endif %}
                ">Вперед</a>
              </li>
        </div>
    </ul>
</nav>
{% endif %}
{% endblock  %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
    </div>
</footer>
{% endblock  %}

goods/templates/goods/product.html
{% extends "base.html" %}

{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                {% if product.image %}
                <img src="{{ product.image.url }}"
                    class="img-fluid" alt="Изображение 1">
                {% else %}
                <img src="{% static "deps/images/Not found image.png" %}"
                    class="img-fluid" alt="Изображение 1">
                {% endif %}
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: {{ product.display_id }}</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            {% if product.image %}
                                <img src="{{ product.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            {% else %}
                                <img src="{% static "deps/images/Not found image.png" %}"
                                    class="img-fluid" alt="Изображение 1">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>{{ product.sell_price }} $</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="{% url "cart:cart_add" %}" class="btn btn-dark add-to-cart"
            data-product-id="{{ product.id }}">
            {% csrf_token %}
            Добавить в корзину</a>
        </div>
    </div>
</div>
{% endblock  %}