goods/urls.py
from django.urls import path
from goods import views 

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.urls import path
from main import views 

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

from shop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views 

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self: 
            return sum(cart.quantity for cart in self)
        return 0
    
class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(verbose_name="Требуеться доставка", default=False)
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(verbose_name="Оплата при получении", default=False)
    is_paid = models.BooleanField(verbose_name="Оплачено", default=False)
    status = models.CharField(max_length=50, verbose_name="Статус заказа", default="В обработке")
    
    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        
    def __str__(self):
        return f"Заказы № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    
    class Meta():
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'  
    
    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password']
        
class UserRegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 
                  'last_name',
                  'username',
                  'email',
                  'password1',
                  'password2']
        
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email"
        )
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import auth, messages
from django.urls import reverse
from carts.models import Cart
from orders.models import Order, OrderItem
from django.db.models import Prefetch

from users.forms import ProfileForm, UserLoginForm, UserRegForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            
            session_key = request.session.session_key
            
            if user:
                auth.login(request,user)
                messages.success(request, f'{username}, Вы вошли в аккаунт')
                
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                
                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
        
    context = {
        'form': form,
    }
    
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegForm(data=request.POST)
        if form.is_valid():
            form.save()
            
            session_key = request.session.session_key
            
            user = form.instance
            auth.login(request, user)
            
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
            
            messages.success(request, f'{user.username}, Вы успешно зарегистрированы и вошли в аккаунт')
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegForm()
        
    context = {
        'form': form,
    }
    
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профиль успешно обновленн')
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    
    orders = (
        Order.objects.filter(user=request.user)
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            )
            .order_by("-id")
    )    
    context = {
        'title': 'Home - Кабинет',
        'form': form,
        'orders': orders,
    }
    
    return render(request, 'users/profile.html', context)

def users_cart(request):
    return render(request, 'users/users_cart.html')

@login_required
def logout(request):
    messages.success(request, 'Вы вышли из аккаунта')
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action='{% url "user:login" %}' method='POST'>
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{ request.GET.nex}}>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input type="text" name='username' value='{% if form.username.value %}{{ form.username.value }}{% endif %}' class="form-control" id="id_username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" name='password' class="form-control" id="id_password" placeholder="Введите ваш пароль" required>
                    </div>
                    
                    {% comment %} {% for item in form %}
                    <div class="mb-3">
                        <label for="{{item.id_for_lable}}" class="form-label">{{item.label}}</label>
                        {{item}}
                    </div>
                    {% endfor %} {% endcomment %}
                    
                    {% comment %} <div class="mb-3">
                        <label for="username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                    </div>{% endcomment %}
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form> 
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url 'users:registration' %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

users/templates/users/logout.html
{% extends "base.html" %}
{% load static %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                <img src="{{ user.image.url }}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% else %}
                                <img src="{% static "deps/images/baseavatar.jpg" %}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name="image"
                                    accept="image/*">
                                {% if form.image.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.image.errors}}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя" 
                                    value="{{ form.first_name.value}}" required>
                                    {% if form.first_name.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.first_name.errors}}
                                    </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name='last_name'
                                    placeholder="Введите вашу фамилию" 
                                    value="{{ form.last_name.value}}" required>
                                    {% if form.last_name.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.last_name.errors}}
                                    </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    placeholder="Введите ваше имя пользователя" 
                                    name='username'
                                    value="{{ form.username.value}}" required>
                                    {% if form.username.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.username.errors}}
                                    </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    placeholder="Введите ваш email *youremail@example.com" 
                                    value="{{ form.email.value}}"
                                    name='email'
                                    required>
                                    {% if form.email.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.email.errors}}
                                    </div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "carts/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                    
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" 
                                    type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse1">
                                        Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус:<strong class="mx-2"> {{ order.status }}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url "goods:product" item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }} $</td>
                                                    <td>{{ item.products_price }} $</td>
                                                    
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action='{% url "user:registration" %}' method='POST'>
                    {%csrf_token%}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name" 
                                name="first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                placeholder="Введите ваше имя" required>
                                {% if form.first_name.errors %}
                                    <div class='alert alert-danger alert-dismissible fade show'>
                                        {{form.first_name.errors}}
                                    </div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                placeholder="Введите вашу фамилию" required>
                            {% if form.last_name.errors %}
                                <div class='alert alert-danger alert-dismissible fade show'>
                                    {{form.last_name.errors}}
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username" name="username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                placeholder="Введите ваше имя пользователя" required>
                            {% if form.username.errors %}
                                <div class='alert alert-danger alert-dismissible fade show'>
                                    {{form.username.errors}}
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email" name="email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                placeholder="Введите ваш email" required>
                            {% if form.email.errors %}
                                <div class='alert alert-danger alert-dismissible fade show'>
                                    {{form.email.errors}}
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1" name="password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                placeholder="Введите пароль" required>
                            {% if form.password1.errors %}
                                <div class='alert alert-danger alert-dismissible fade show'>
                                    {{form.password1.errors}}
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2" 
                                name="password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                placeholder="Подтвердите пароль" required>
                            {% if form.password2.errors %}
                                <div class='alert alert-danger alert-dismissible fade show'>
                                    {{form.password2.errors}}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
{% user_carts request as carts %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}